function DEPTevb1000map = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DEPTEVB1000MAP = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  DEPTEVB1000MAP = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  DEPTevb1000map = importfile("/Users/alessandrobianchiceriani/Desktop/Scrivania_MPB/ALE_VARIE_DONTTOUCH/UNITN/MAGISTRALE/Secondo_Anno/Distributed_Estimation/distributed-track-loc/DEPT_evb1000_map.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Dec-2025 10:49:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["NodeId", "Zone", "Coordinates", "evb1000"];
opts.VariableTypes = ["double", "categorical", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Coordinates", "evb1000"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Zone", "Coordinates", "evb1000"], "EmptyFieldRule", "auto");

% Import the data
DEPTevb1000map = readtable(filename, opts);

end